### ISSUE TITLE
Drawing an AUV with the same name doesn't refresh it...

### ISSUE THREAD

**Issue by msis** [ENSTABretagneRobotics/VIBES#70]
... but draws another object with the same name.

``` C++
  vibes::drawAUV(0,0,180,2.0,"blue[darkGreen]",vibesParams("name","AUV"));
  vibes::drawAUV(10,10,0,2.0,"blue[darkGreen]",vibesParams("name","AUV"));
```

**Comment by dvinc** [comment]
In fact, it "anonymises" the previous "AUV" object, and creates a new object called AUV.
I think this behavior came as a "feature" :smile: of a previous bug fix in named-objects deletion.
I thought named objects could be deleted, or have their properties modified (even geometrical properties) with the setObjectProperty(ies) functions.
We need to explicitly state what happens when drawXXX is called with an existing object name, and when renaming an object to an existing name. I think that discarding the older object is a good option, since it avoids the need to learn the use of setObjectProperties for beginners.
I propose the following, which should be added to the documentation (as soon as it's fixed):
"When a drawing function 'drawXXX' is called with the 'name' property set to the name of an existing object in the figure, the previous object is removed and replaced by the new drawing."
"When an object is renamed (with 'setObjectProperty' or 'setObjectProperties') to the name of an existing object in the figure, the previous object is deleted and only the renamed object is kept."
Now that the expected behavior is defined, I'll tag this as a bug.

**Comment by msis** [comment]
OK! Works for me!

**Comment by nicolaje** [comment]
Sounds good to me.
