### ISSUE TITLE
How to install Vibes?

### ISSUE THREAD

**Issue by Jordan08** [ENSTABretagneRobotics/VIBES#85]
It is possible to indicate on your website (or somewhere) how to install Vibes?
Can you add an small script "install.sh" which install all the packages that we need and then install Vibes?

Thank you

**Comment by nicolaje** [comment]
Hi @Jordan08 ,

Self-contained (dependency free) VIBes executables can be downloaded on the releases page of VIBes:
https://github.com/ENSTABretagneRobotics/VIBES/releases
currently for OSX and Windows. Since I believe you work with Linux, a Linux executable is coming (mea culpa).

If you want to build VIBes from source on Linux you should install Qt5 and cmake:

sudo apt-get install cmake qt5-default libqt5svg5-dev

then cd in the "viewer" directory of the source code and run:

mkdir build && cd build
cmake ..
make

it should work.

Actions required to close this issue:
- [ ] provide a Linux binary
- [ ] add build instructions on the VIBes Github page

**Comment by Jordan08** [comment]
Is it possible to get this view line in a README file or in  script install.sh at the root of the github project.

Thank you

**Comment by nicolaje** [comment]
Done. Let me know if you still can't build from source.
