### ISSUE TITLE
box accuracy limited to 6 digits w/o outward rounding

### ISSUE THREAD

**Issue by oheim** [ENSTABretagneRobotics/VIBES#97]
The C++ client-api produces the following action when I call `vibes.drawBox (1+eps, 1-eps, e, pi)`. The box is illegal (x_lb > x_ub), but the information is lost in the JSON file. Numbers are limited to decimal format with 6 digits. Also, y_ub is not rounded outwards. I would have expected 3.14160 as a rigorous upper boundary.
````
{"action":"draw", "figure":"default", "shape":{"bounds":[1,1,2.71828,3.14159], "format":"", "type":"box"}}
````

Would you consider this an error or is the accuracy good enough for plotting?

**Comment by dvinc** [comment]
We limited numbers to 6 significant digits for compactness, since commands are written to a file.
As vibes is only intended for graphical display, we thought it was enough accuracy for plotting. Since the correct rounding to depends on the signification of the box, we decided to keep default rounding (outwards rounding should be applied to boxes that cover a solution, but inwards rounding should be applied to boxes that are included in the solution).

We can increase C++ API output precision to allow full double precision (I think it needs at least 16 decimals), but I'm not sure full precision is kept during the drawing process.

**Comment by oheim** [comment]
@dvinc, I can agree with that.

> We can increase C++ API output precision to allow full double precision (I think it needs at least 16 decimals), but I'm not sure full precision is kept during the drawing process.

If you wanted to improve this, you should serialize the double precision numbers in hexadecimal form (is that supported by JSON?).
